AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: PixelPark API Infra Deployment.

Resources:
  # ========== Cognito ==========

  PixelParkUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: PixelParkUserPool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false

  PixelParkUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: PixelParkAppClient
      UserPoolId: !Ref PixelParkUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH

Outputs:
  PixelParkUserPoolId:
    Value: !Ref PixelParkUserPool
    Export:
      Name: PixelParkUserPoolId
  PixelParkUserPoolArn:
    Value: !GetAtt PixelParkUserPool.Arn
    Export:
      Name: PixelParkUserPoolArn
  PixelParkUserPoolClientId:
    Value: !Ref PixelParkUserPoolClient
    Export:
      Name: PixelParkUserPoolClientId
