AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: PixelPark Lambda Deployment.

Globals:
  Function:
    Runtime: python3.11
    Timeout: 10
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        DB_NAME: !Ref DbName
        DB_USER: !Ref DbUser
        DB_HOST: !Ref DbHost
        DB_PASSWORD: !Ref DbPassword
        COGNITO_CLIENT_ID: !ImportValue PixelParkUserPoolClientId

Parameters:
  DbName:
    Type: String
  DbUser:
    Type: String
  DbHost:
    Type: String
  DbPassword:
    Type: String

Resources:
  # ========== API Gateway ==========

  PixelParkApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: PixelPark
      StageName: dev
      EndpointConfiguration: REGIONAL
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !ImportValue PixelParkUserPoolArn
      TracingEnabled: true
      # Cors:
      #   AllowMethods: "'GET,OPTIONS'"
      #   AllowOrigins: "'*'"

  # ========== Products APIs ==========

  # GET /products
  ProductsGetAllFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_functions/products/getAll.lambda_handler
      Layers:
        - arn:aws:lambda:us-west-1:809604783960:layer:PixelPark_layer:3
      Events:
        GetProducts:
          Type: Api
          Properties:
            RestApiId: !Ref PixelParkApi
            Path: /products
            Method: GET
            Auth:
              Authorizer: NONE

  # GET /products/{id}
  ProductsGetByIdFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_functions/products/getById.lambda_handler
      Layers:
        - arn:aws:lambda:us-west-1:809604783960:layer:PixelPark_layer:3
      Events:
        GetProductById:
          Type: Api
          Properties:
            RestApiId: !Ref PixelParkApi
            Path: /products/{id}
            Method: GET
            Auth:
              Authorizer: NONE

  # ========== Auth APIs ==========

  # POST /auth/register
  UserRegisterFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_functions/auth/register.lambda_handler
      Layers:
        - arn:aws:lambda:us-west-1:809604783960:layer:PixelPark_layer:3
      Events:
        RegisterUser:
          Type: Api
          Properties:
            RestApiId: !Ref PixelParkApi
            Path: /auth/register
            Method: POST
            Auth:
              Authorizer: NONE

  # POST /auth/confirm-registration
  UserConfirmFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_functions/auth/confirm_register.lambda_handler
      Layers:
        - arn:aws:lambda:us-west-1:809604783960:layer:PixelPark_layer:3
      Events:
        ConfirmUser:
          Type: Api
          Properties:
            RestApiId: !Ref PixelParkApi
            Path: /auth/confirm-registration
            Method: POST
            Auth:
              Authorizer: NONE

  # POST /auth/resend-confirmation
  ResendConfirmFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_functions/auth/confirm_resend.lambda_handler
      Events:
        ConfirmUser:
          Type: Api
          Properties:
            RestApiId: !Ref PixelParkApi
            Path: /auth/resend-confirmation
            Method: POST
            Auth:
              Authorizer: NONE

  # POST /auth/forgot-password
  ForgotPasswordFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_functions/auth/forgot_password.lambda_handler
      Events:
        ConfirmUser:
          Type: Api
          Properties:
            RestApiId: !Ref PixelParkApi
            Path: /auth/forgot-password
            Method: POST
            Auth:
              Authorizer: NONE

  # POST /auth/confirm-reset-password
  PasswordResetConfirmFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_functions/auth/confirm_reset_password.lambda_handler
      Events:
        ConfirmUser:
          Type: Api
          Properties:
            RestApiId: !Ref PixelParkApi
            Path: /auth/confirm-reset-password
            Method: POST
            Auth:
              Authorizer: NONE

  # POST /auth/login
  UserLoginFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_functions/auth/login.lambda_handler
      Layers:
        - arn:aws:lambda:us-west-1:809604783960:layer:PixelPark_layer:3
      Events:
        LoginUser:
          Type: Api
          Properties:
            RestApiId: !Ref PixelParkApi
            Path: /auth/login
            Method: POST
            Auth:
              Authorizer: NONE

  # POST /auth/logout
  UserLogoutFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_functions/auth/logout.lambda_handler
      Events:
        LogoutUser:
          Type: Api
          Properties:
            RestApiId: !Ref PixelParkApi
            Path: /auth/logout
            Method: POST
            Auth:
              Authorizer: NONE

  # ========== User APIs ==========

  UserProfileFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_functions/profile/getUser.lambda_handler
      Layers:
        - arn:aws:lambda:us-west-1:809604783960:layer:PixelPark_layer:3
      Events:
        GetUserProfile:
          Type: Api
          Properties:
            RestApiId: !Ref PixelParkApi
            Path: /profile
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
