name: Deploy AWS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install SAM CLI
        run: pip install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: SAM Build & Deploy Infra Stack
        run: |
          sam build -t template_infra.yaml
          sam deploy \
            --template-file template_infra.yaml \
            --stack-name pixelpark-infra-dev \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset \
            --resolve-s3

      - name: SAM Build & Deploy Lambda Stack
        run: |
          sam build -t template_lambda.yaml
          sam deploy \
            --template-file template_lambda.yaml \
            --stack-name pixelpark-lambda-dev \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset \
            --resolve-s3 \
            --parameter-overrides \
              DbName='${{ secrets.DB_NAME }}' \
              DbUser='${{ secrets.DB_USER }}' \
              DbHost='${{ secrets.DB_HOST }}' \
              DbPassword='${{ secrets.DB_PASSWORD }}'
